name: Validate draft
on:
  pull_request:

jobs:
  validate-draft:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Validate Quest
        uses: trywilco/uploadQuestAction@main
        with:
          quest-editor-user-token: ${{ secrets.QUESTS_EDITOR_TOKEN }}
          quest-editor-user-email: quests@wilcohq.com
          only-validate: true
